# vim:set ft=dockerfile:

FROM debian:stable-slim

RUN set -eux; apt-get update; apt-get install -y --no-install-recommends curl make ca-certificates build-essential libssl-dev pkg-config libpq-dev
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > installer
RUN sh installer -y
COPY . /tmp/build
WORKDIR /tmp/build
RUN ./in_docker_build_script.sh


FROM debian:stable-slim

RUN set -eux; apt-get update; apt-get install -y --no-install-recommends libpq5 libc6 libgcc1
COPY --from=0 /tmp/build/target/release/channel_builder /usr/local/bin

WORKDIR /usr/local/share/channel_builder
ENTRYPOINT ["channel_builder"]

EXPOSE 3031
